<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<ApplicationIcon>Assets\icon-M-03.ico</ApplicationIcon>
		<Company>Özalp Döndüren</Company>
		<Product>Ozz Markdown</Product>
		<Description>Ozz Markdown is a lightweight Markdown viewer and editor.</Description>
		<Copyright>Copyright © 2026</Copyright>
		
		<Version>0.1.8</Version>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Assets\icon-M-03.ico" />
		<Resource Include="Assets\icon-doc-M-03.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\OzzMarkdown.Core\OzzMarkdown.Core.csproj" />
	  <ProjectReference Include="..\OzzMarkdown.i18n\OzzMarkdown.i18n.csproj" />
	  <ProjectReference Include="..\OzzWpf.Core\OzzWpf.Core.csproj" />
	</ItemGroup>

</Project>
