using Markdig;
using OzzMarkdown.Core.Helpers;

namespace OzzMarkdown.Core
{
    public class MarkdownHtmlRenderer
    {
        private readonly MarkdownPipeline _pipeline;
        private readonly string VirtualHostName;
        private readonly string TempFolderName;
        private List<string> _tempHtmlFiles = new List<string>();

        public MarkdownHtmlRenderer(string virtualHostName, string tempFolderName)
        {
            _pipeline = new MarkdownPipelineBuilder()
           .UseAdvancedExtensions()
           .UseTableOfContent()
           .Build();

            VirtualHostName = virtualHostName;
            TempFolderName = tempFolderName;
        }

        public void CleanupTempFiles()
        {
            foreach (var file in _tempHtmlFiles)
            {
                try
                {
                    if (File.Exists(file))
                    {
                        File.Delete(file);
                    }
                }
                catch
                {
                    //ignore any exceptions during cleanup
                }
            }
            _tempHtmlFiles.Clear();
        }

        public string TempFolder
        {
            get
            {
                string tmpFolder = Path.Combine(Path.GetTempPath(), TempFolderName);
                if (!Directory.Exists(tmpFolder))
                    Directory.CreateDirectory(tmpFolder);

                return tmpFolder;
            }
        }

        public string RenderToTempFileUrl(string markdown, MarkdownTheme theme, bool generateToc)
        {
            if (generateToc)
                markdown = $"[TOC]\n\n{markdown}";

            EnsureStaticAssetsWritten(theme);

            string html = Markdown.ToHtml(markdown, _pipeline);
            string finalHtml = WrapHtml(html, theme, generateToc);

            string tempHtmlFile = Path.Combine(TempFolder, $"markdown_{Guid.NewGuid():N}.html");
            File.WriteAllText(tempHtmlFile, finalHtml, System.Text.Encoding.UTF8);
            _tempHtmlFiles.Add(tempHtmlFile);
            string fileName = Path.GetFileName(tempHtmlFile);

            return $"https://{VirtualHostName}/{fileName}";
        }

        /// <summary>
        /// Writes the Prism.js script and the theme's CSS assets to the temp folder once,
        /// so generated HTML pages can reference them by a stable URL instead of embedding
        /// them inline on every render (allows the browser to cache them across navigations).
        /// </summary>
        private void EnsureStaticAssetsWritten(MarkdownTheme theme)
        {
            var (jsResourceName, jsFileName) = MarkdownThemeProvider.GetPrismJsAsset();
            WriteAssetIfMissing(jsResourceName, jsFileName);

            foreach (var (cssResourceName, cssFileName) in MarkdownThemeProvider.GetPrismCssAssets(theme))
            {
                WriteAssetIfMissing(cssResourceName, cssFileName);
            }
        }

        private void WriteAssetIfMissing(string resourceName, string fileName)
        {
            string filePath = Path.Combine(TempFolder, fileName);
            if (!File.Exists(filePath))
            {
                File.WriteAllText(filePath, ResourceLoader.Load(resourceName), System.Text.Encoding.UTF8);
            }
        }

        /// <summary>
        /// Layout-only CSS (theme-independent) that pins the table-of-contents &lt;nav&gt;
        /// generated by AutoCore.MarkdigToc to the right side of the document as a
        /// self-scrolling sidebar, and reserves space for it so it never overlaps content.
        /// </summary>
        private const string TocSidebarCss = @"
:root {
    --toc-width: 280px;
}

body.has-toc-sidebar {
    margin-left: var(--toc-width);
}

.toc-sidebar {
    position: fixed;
    top: 0;
    left: 0;
    width: var(--toc-width);
    height: 100vh;
    overflow-y: auto;
    box-sizing: border-box;
    padding: 6px;
    border-right: 1px solid rgba(128, 128, 128, 0.3);
    background: inherit;
    z-index: 100;
}

.toc-sidebar nav {
    font-size: 0.9em;
}

.toc-sidebar nav ul {
    list-style: none;
    margin: 0;
    padding-left: 6px;
}

.toc-sidebar nav > ul {
    padding-left: 0;
}

.toc-sidebar nav li {
    margin: 0;
}

.toc-sidebar nav a {
    display: block;
    padding: 2px 0;
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}

.toc-resize-handle {
    position: absolute;
    top: 0;
    right: -3px;
    width: 6px;
    height: 100%;
    cursor: col-resize;
    z-index: 101;
}

.toc-resize-handle:hover,
.toc-resize-handle.resizing {
    background: rgba(128, 128, 128, 0.4);
}

@media (max-width: 900px) {
    body.has-toc-sidebar {
        margin-left: 0;
    }

    .toc-sidebar {
        position: static;
        width: auto;
        height: auto;
        max-height: 40vh;
        border-right: none;
        border-bottom: 1px solid rgba(128, 128, 128, 0.3);
        margin-bottom: 16px;
    }

    .toc-resize-handle {
        display: none;
    }
}";

        /// <summary>
        /// Wraps the first top-level &lt;nav&gt; element (the AutoCore.MarkdigToc output) in a
        /// scrollable, resizable sidebar container and marks &lt;body&gt; so the reserved-space
        /// CSS rule applies. A drag handle on the sidebar's right edge lets the user resize
        /// it by updating the shared <c>--toc-width</c> CSS variable. No-op when the document
        /// has no table of contents.
        /// </summary>
        private const string TocSidebarScript = @"
(function initTocSidebar() {
    var nav = document.querySelector('body > nav');
    if (!nav) return;

    var sidebar = document.createElement('div');
    sidebar.className = 'toc-sidebar';
    nav.parentNode.insertBefore(sidebar, nav);
    sidebar.appendChild(nav);

    nav.querySelectorAll('a').forEach(function (link) {
        if (!link.hasAttribute('title')) {
            link.title = link.textContent.trim();
        }
    });

    var handle = document.createElement('div');
    handle.className = 'toc-resize-handle';
    sidebar.appendChild(handle);

    document.body.classList.add('has-toc-sidebar');

    var minWidth = 180;
    var maxWidth = 600;
    var isResizing = false;

    function setWidth(px) {
        var clamped = Math.min(maxWidth, Math.max(minWidth, px));
        document.documentElement.style.setProperty('--toc-width', clamped + 'px');
    }

    handle.addEventListener('mousedown', function (e) {
        isResizing = true;
        handle.classList.add('resizing');
        document.body.style.userSelect = 'none';
        e.preventDefault();
    });

    document.addEventListener('mousemove', function (e) {
        if (!isResizing) return;
        setWidth(e.clientX);
    });

    document.addEventListener('mouseup', function () {
        if (!isResizing) return;
        isResizing = false;
        handle.classList.remove('resizing');
        document.body.style.userSelect = '';
    });
})();";

        private string WrapHtml(string html, MarkdownTheme theme, bool generateToc)
        {
            string cssLinks = string.Join("\n", MarkdownThemeProvider.GetPrismCssAssets(theme)
                .Select(asset => $"<link rel='stylesheet' href='https://{VirtualHostName}/{asset.FileName}'>"));

            return $@"<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'>
<style>
{theme.Css}
{(generateToc ? TocSidebarCss : string.Empty)}
</style>
{cssLinks}
</head>
<body>
{html}
<script src='https://{VirtualHostName}/{MarkdownThemeProvider.GetPrismJsAsset().FileName}'></script>
<script>
{(generateToc ? TocSidebarScript : string.Empty)}
document.querySelectorAll('pre code').forEach(block => {{
    if (!block.className.includes('language-')) {{
        block.classList.add('language-csharp'); // default fallback
    }}
}});
Prism.highlightAll();
</script>
</body>
</html>";
        }
    }
}
